version: '3.3'

volumes:
  pg_data:

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
#    volumes:
#      - pg_data:/var/lib/postgresql/data
    ports:
      - 5462:5432
